In [170]:
import torch
import numpy as np

In [171]:
data = [1,2,3]
x_data = torch.tensor(data)

In [172]:
x_data = torch.from_numpy(np.array(data))

In [173]:
x_data

tensor([1, 2, 3])

In [174]:
torch.rand((2,2))

tensor([[0.2991, 0.0099],
        [0.1540, 0.2687]])

In [175]:

torch.ones_like(x_data)

tensor([1, 1, 1])

In [176]:

torch.stack([torch.ones_like(x_data), torch.ones_like(x_data), torch.ones_like(x_data)], dim=1)

tensor([[1, 1, 1],
        [1, 1, 1],
        [1, 1, 1]])

In [177]:
    
torch.stack([torch.ones_like(x_data), torch.ones_like(x_data), torch.ones_like(x_data)], dim=1).add_(3)

tensor([[4, 4, 4],
        [4, 4, 4],
        [4, 4, 4]])

In [178]:
a = torch.tensor([2., 3.], requires_grad=True)
b = torch.tensor([6., 4.], requires_grad=True)
Q = 3*a**3 - b**2

In [179]:
external_grad = torch.tensor([1., 1.])
Q.backward(gradient=external_grad)

In [180]:
print(9*a**2 == a.grad)
print(-2*b == b.grad)


tensor([True, True])
tensor([True, True])


In [181]:
import torch.nn as nn
import torch.nn.functional as F

In [182]:
class MyNet(nn.Module):
    def __init__(self):
        super().__init__()
        self.fc1 = nn.Linear(1, 5)
    
    def forward(self, x):
        C1 = self.fc1(x)
        C2 = C1 * C1
        return C2

In [183]:

net = MyNet()
print(net)

MyNet(
  (fc1): Linear(in_features=1, out_features=5, bias=True)
)


In [184]:
out = net.forward(torch.tensor([10.0]))
target = torch.rand(5)
target = target * target * 5


In [185]:
out.view(1, -1)

tensor([[13.0419,  0.2554,  5.3082, 73.1446,  7.1198]],
       grad_fn=<ViewBackward0>)

In [186]:
target.view(1, -1)

tensor([[0.3389, 1.5849, 3.0595, 1.7087, 1.5898]])

In [187]:
criterion = nn.MSELoss()
loss = criterion(out, target)
print(loss)

tensor(1060.3723, grad_fn=<MseLossBackward0>)


In [188]:
import torch.optim as optim

# create your optimizer
optimizer = optim.SGD(net.parameters(), lr=0.01)



In [189]:
net.parameters()

<generator object Module.parameters at 0x1540967a0>

In [190]:
for i in range(10):                                                                                                                                                       
    optimizer.zero_grad()                                                                                                                                                   
    out = net(torch.tensor([10.0]))     # recompute every step                                                                                                              
    loss = criterion(out, target)                                                                                                                                           
    loss.backward()                                                                                                                                                         
    optimizer.step()                                                                                                                                                        
    print(loss.item())   

1060.372314453125
11075160064.0
1.4474489389984889e+31
inf
inf
nan
nan
nan
nan
nan
