In [170]:
import torch
import numpy as np

In [171]:
data = [1,2,3]
x_data = torch.tensor(data)

In [172]:
x_data = torch.from_numpy(np.array(data))

In [173]:
x_data

tensor([1, 2, 3])

In [174]:
torch.rand((2,2))

tensor([[0.2991, 0.0099],
        [0.1540, 0.2687]])

In [175]:

torch.ones_like(x_data)

tensor([1, 1, 1])

In [176]:

torch.stack([torch.ones_like(x_data), torch.ones_like(x_data), torch.ones_like(x_data)], dim=1)

tensor([[1, 1, 1],
        [1, 1, 1],
        [1, 1, 1]])

In [177]:
    
torch.stack([torch.ones_like(x_data), torch.ones_like(x_data), torch.ones_like(x_data)], dim=1).add_(3)

tensor([[4, 4, 4],
        [4, 4, 4],
        [4, 4, 4]])

In [178]:
a = torch.tensor([2., 3.], requires_grad=True)
b = torch.tensor([6., 4.], requires_grad=True)
Q = 3*a**3 - b**2

In [179]:
external_grad = torch.tensor([1., 1.])
Q.backward(gradient=external_grad)

In [180]:
print(9*a**2 == a.grad)
print(-2*b == b.grad)


tensor([True, True])
tensor([True, True])


In [181]:
import torch.nn as nn
import torch.nn.functional as F

In [294]:
class MyNet(nn.Module):
    def __init__(self):
        super().__init__()
        self.fc1 = nn.Linear(1, 5)
    
    def forward(self, x):
        C1 = self.fc1(x)
        C2 = C1 * C1
        return C2

In [295]:

net = MyNet()
print(net)

MyNet(
  (fc1): Linear(in_features=1, out_features=5, bias=True)
)


In [296]:
out = net.forward(torch.tensor([10.0]))
target = torch.rand(5)
target = target * target * 5


In [297]:
out.view(1, -1)

tensor([[24.6896, 18.0407,  3.2101,  0.4149,  0.6760]],
       grad_fn=<ViewBackward0>)

In [298]:
target.view(1, -1)

tensor([[4.2104, 3.5652, 1.2903, 4.2980, 2.6080]])

In [299]:
criterion = nn.MSELoss()
loss = criterion(out, target)
print(loss)

tensor(130.2872, grad_fn=<MseLossBackward0>)


In [300]:
import torch.optim as optim

# create your optimizer
optimizer = optim.Adam(net.parameters(), lr=0.01)



In [301]:
net.parameters()

<generator object Module.parameters at 0x153f81b60>

In [309]:
for i in range(1000):                                                                                                                                                       
    optimizer.zero_grad()                                                                                                                                                   
    out = net(torch.tensor([10.0]))     # recompute every step                                                                                                              
    loss = criterion(out, target)                                                                                                                                           
    loss.backward()                                                                                                                                                         
    optimizer.step()                                                                                                                                                        
    print(loss.item())   

0.043814126402139664
0.04120035469532013
0.038693591952323914
0.036247268319129944
0.03382621705532074
0.03141424432396889
0.02901459112763405
0.026649970561265945
0.024355480447411537
0.022171635180711746
0.020136810839176178
0.01827823929488659
0.01660684309899807
0.015115322545170784
0.013780295848846436
0.012568737380206585
0.0114462710916996
0.010385477915406227
0.009371678344905376
0.00840478390455246
0.007495952304452658
0.006662496365606785
0.005920145660638809
0.005277158226817846
0.0047311638481915
0.004269519820809364
0.003872861620038748
0.003520286874845624
0.0031946487724781036
0.0028854396659880877
0.002590374555438757
0.0023127454333007336
0.0020589097402989864
0.0018347387667745352
0.0016428509261459112
0.0014819346833974123
0.0013469615951180458
0.0012313005281612277
0.00112791801802814
0.0010315388208255172
0.0009391239727847278
0.0008498785318806767
0.0007645903970114887
0.0006848358316347003
0.000612118688877672
0.0005472523625940084
0.0004901922075077891
0.0004402

In [313]:
                                                                                                                                            
print(i, "loss=", loss.item(),                                                                                                                                          
        "w=", net.fc1.weight.data.flatten().tolist(),                                                                                                                     
        "b=", net.fc1.bias.data.tolist())

999 loss= 1.4210854715202004e-12 w= [0.2820793688297272, -0.3044404089450836, 0.15673767030239105, -0.23123984038829803, -0.059661708772182465] b= [-0.7688679099082947, 1.156229853630066, -0.4314412772655487, 0.23922684788703918, -1.0183273553848267]
